#! /bin/zsh
# -*- mode: bash -*- 

export DOTFILES=$HOME/.dotfiles

# "Compile" a bunch of file together. Ignores syntax. 

typeset -U zshenv_files
zshenv_files=($DOTFILES/**/*.zshenv)
echo $zshenv_files
cat ${zshenv_files} > ~/scratch/x.zshenv

typeset -U zshrc_files
zshrc_files=($DOTFILES/**/*.zsh)
echo $zshrc_files
cat ${zshrc_files} > ~/scratch/x.zshrc_files



## END OF LINE ##
