#! /bin/zsh

set -e 

# Special case the fleet deployment - we can't use the standard symlink script (yet) and we have to 
# leave junk out. (I see no point in deploying scripts/config to 4000 machines that don't need it).

if [[ $HOSTNAME != thm.desktop.amazon.com ]] ; then
    echo "not on desktop - should only run there"
    exit 1 
fi

# Get to the glacier homes workspace 
cd ~/ws/homes

# Start a fresh copy
rm -rf .dotfiles
cp -a ~/.dotfiles .dotfiles

# Manipulate the copied dotfiles.
cd .dotfiles

# Remove junk not needed
# Dont remove .dotfiles/dotfiles itself just yet.
rm -f LICENSE.md
rm -f README.md

rm -rf .git*
rm -rf emacs 
rm -rf git
rm -rf homebrew
rm -rf osx
rm -rf future
rm -rf python

# Move the fleet cleanup script into place 
# Obviously we can't have this in the real place as we'd delete half of .dotfiles every time we logged in.
cp dotfiles/glacierhomes_scrubber 1st/fleet.cleanup

dotfiles/make_symlinks

rm -rf dotfiles

## END OF LINE ##
