#! /usr/bin/env bash
#
# Run all dotfiles installers.

# WARNING: This script must not itself be called install.sh
set -e   # crummy error checking - exit on non-zero

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
