#! /usr/bin/env fish  

set help "
Usage: dots builder [options] suffix target_file
Options:
  -d, --debug        Enable debug mode
  -h, --help         Show this help
"

source $DOTS/libexec/dots/lib-common.fish
or begin
	echo "FATAL: Unable to source lib-common.fish library" 
	exit 10
end

# this script exists solely to call the dots_verify_base_config function in lib-common.fish
dots_verify_base_config

## END OF LINE ##

