#! /usr/bin/env fish

set help "
Usage: dots check
Options:
    -d, --debug        Enable debug mode
    -h, --help         Show this help
"

source $DOTS/libexec/dots/common-lib.fish
or begin
    echo "FATAL: Unable to source common-lib.fish library"
    exit 10
end

# this script exists solely to call the dots_verify_base_config function in lib-common.fish
echo "==> Checking base config..."
dots_require_base_config

## END OF LINE ##
