#! /usr/bin/env fish

set help "
Usage: dots builder [options] suffix target_file
Options:
    -d, --debug        Enable debug mode
    -h, --help         Show this help
"

source $DOTS/libexec/dots/common-lib.fish
or begin
    echo "FATAL: Unable to source common-lib.fish library"
    exit 10
end

dots builder .fish $DOTS_LOCAL/config%fish%config.fish.symlink

## END OF LINE ##