#! /usr/bin/env fish

set help "
Usage: dots builder [options] suffix target_file
Options:
    -d, --debug        Enable debug mode
    -h, --help         Show this help
"

source $DOTS/libexec/dots/common-lib.fish
or begin
    echo "FATAL: Unable to source common-lib.fish library"
    exit 10
end

echo "ERROR: This script is not yet implemented."
exit 1

# rename gitconfig.symlink to .... gitconfig.original
# COPY original to $DOTS_LOCAL
# git config $FILENAME set name and email and whatnot
# NOW the linker runs.

# Meh.

## END OF LINE ##
