#! /usr/bin/env fish

set -g HELP "
Usage: $(status basename) [options...]

make symlinks for *.symlink files.

Optional Arguments
        --debug              Print debug information
    -h, --help               Print this help
"

set -g DOTS_LIBEXEC $DOTS/libexec/dots
# TODO: migrate this to the common-lib ...
function fish_command_not_found
    exit 12
end

# FIXME: check for DOTS before using
source $DOTS_LIBEXEC/common-lib.fish
or begin
    echo "FATAL: could not source common-lib.fish -- exiting program..."
    exit 11
end

function install_dotfiles
    # info 'installing dotfiles'

    for src in (find -H "$DOTS" "$DOTS_LOCAL" -maxdepth 2 -name '*.symlink' -not -path '*.git*')

        # dst="$HOME/.$(basename "${src%.*}")"
        set -l dst $HOME/.(string replace -r '\.symlink$' '' (basename $src))
        echo ln -s $src $dst

    end

end

function main
    install_dotfiles

    echo ''
    echo '  All installed!'
end

main $argv

# END OF LINE #
