# Brew itself - do these first.
tap "homebrew/bundle"
brew "mas"


#
# Homebrew
#

# Modern shell world
brew "fish"
brew "bat"
brew "btop"
brew "dust"
brew "fd"
brew "jq"
brew "ripgrep"
brew "pwgen"
brew "figlet"
brew "pass"

# MacOS Compatibility
brew "base64"

brew "grep"
brew "joe"
brew "make"
brew "pinentry-mac"
brew "gnu-sed"
brew "zlib"

# Enhance MacOS
brew "opensc"
brew "switchaudio-osx"
# brew "wallpaper"   manage MacOS wallpapers from CLI

# General Development
brew "direnv"
brew "gh"
brew "git"
brew "git-who"
brew "minisign"
brew "pkgconf"
brew "pandoc"
brew "signify-osx"
brew "yamllint"

# Diffing hell
brew "tkdiff"
brew "diffoscope"

# Bash / ZSH Development
brew "shellcheck"
brew "shfmt"

# Go Development
brew "go"

# Python Development
brew "black"
brew "docutils"
brew "isort"
brew "pipx"
brew "pygments"
brew "python@3.10"
brew "python@3.11"
brew "virtualenv"

# Cloud
brew "awscli"

# Hashicorp - add ons to the cloud
tap "hashicorp/tap"
brew "hashicorp/tap/packer"
brew "hashicorp/tap/terraform"
brew "hashicorp/tap/vault"
brew "tflint"
brew "packer-completion"


#
# Cask: MacOS GUI Apps
#
cask "appcleaner"
cask "basictex"

#
# VSCode Stuff
#

# General
vscode "aaron-bond.better-comments"
vscode "npxms.hide-gitignored"
vscode "pdconsec.vscode-print"
vscode "editorconfig.editorconfig"
vscode "eliostruyf.vscode-hide-comments"
vscode "chrislajoie.vscode-modelines"
vscode "github.vscode-github-actions"
vscode "gruntfuggly.todo-tree"
vscode "wdawson.better-kill-ring"
vscode "vscode-icons-team.vscode-icons"
vscode "rslfrkndmrky.rsl-vsc-focused-folder"
vscode "stkb.rewrap"
vscode "streetsidesoftware.code-spell-checker"

# Hashicorp
vscode "4ops.packer"
vscode "hashicorp.hcl"
vscode "hashicorp.terraform"

# Theme Junk
vscode "azemoh.one-monokai"
vscode "emmanuelbeziat.vscode-great-icons"
vscode "equinusocio.vsc-material-theme-icons"
vscode "github.github-vscode-theme"
vscode "pkief.material-icon-theme"

# AI

vscode "github.copilot"
vscode "github.copilot-chat"



# Markdown
vscode "bierner.markdown-preview-github-styles"
vscode "davidanson.vscode-markdownlint"

# Go
vscode "golang.go"

# Saltstack
vscode "korekontrol.saltstack"
vscode "redhat.vscode-yaml"
vscode "wholroyd.jinja"

# Python
vscode "ms-python.debugpy"
vscode "ms-python.pylint"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"

# Make and Build Tools
vscode "ms-vscode.makefile-tools"

# Fish
vscode "bmalehorn.vscode-fish"
vscode "ndonfris.fish-lsp"


#
# Mac App Store Apps
#

mas "Things", id: 904280696
mas "MarkEdit", id: 1669953820
mas "Smart Card Utility", id: 1444710309
mas "Timeless", id: 1017047129
mas "Menubar Countdown", id: 1485343244
mas "Keynote", id: 409183694
mas "Klokki Slim", id: 1459795140
mas "CompareMerge2", id: 1459748650
mas "Password Factory", id: 888806818
mas "Dropzone 3", id: 695406827
mas "DaisyDisk", id: 411643860
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "SubnetCalc", id: 412946682
mas "Get Plain Text", id: 508368068
mas "Compare Folders", id: 816042486
mas "Countdowns", id: 926707738
mas "Microsoft Remote Desktop", id: 1295203466
mas "CotEditor", id: 1024640650
mas "AS TimerPRO", id: 1486015273
