words = [
    "GOPRIVATE",
    "ISSO",
    "Libre",
    "NHGRI",
    "Openssh",
    "Submatch",
    "groff",
    "homebrew",
    "mandoc",
    "markdownlint",
    "openssl",
    "shellcheck",
    "subcmd",
]
