words = [
    "ARN",
    "CIT's",
    "CLI",
    "Cyberark",
    "GOPRIVATE",
    "Hashicorp",
    "IAM",
    "ISSO",
    "KMS",
    "Libre",
    "NHGRI",
    "Openssh",
    "STS",
    "Submatch",
    "clu",
    "groff",
    "homebrew",
    "itb",
    "mandoc",
    "markdownlint",
    "openssl",
    "rollout",
    "shellcheck",
    "sso",
    "subcmd",
]
