PASSWORD_STORE_ENABLE_EXTENSIONS=true
#PASSWORD_STORE_EXTENSIONS_DIR=/usr/local/lib/password-store/extensions

export PASSWORD_STORE_ENABLE_EXTENSIONS
#export PASSWORD_STORE_EXTENSIONS_DIR

## END OF LINE ##
